### ISSUE TITLE
Change package name to @hapi/eslint-plugin

### ISSUE THREAD

**Issue by kanongil** [hapijs/eslint-plugin-hapi#21]
Following #20, I would like this package to be renamed to `@hapi/eslint-plugin`, as this will create a nicer interface to eslint.

With this change:

* Config `plugin:@hapi/hapi/recommended` => `plugin:@hapi/recommended`
* Plugin `@hapi/hapi` => `@hapi`
* Rule `@hapi/hapi/capitalize-modules` => `@hapi/capitalize-modules`
* Rule `@hapi/hapi/for-loop` => `@hapi/for-loop `
* Rule `@hapi/hapi/no-var` => `@hapi/no-var`
* Rule `@hapi/hapi/scope-start` => `@hapi/scope-start`
* Rule `@hapi/hapi/no-arrowception` => `@hapi/no-arrowception`

**Comment by kanongil** [comment]
FYI, this rename will probably necessitate a breaking change in lab as well, since any attempt to disable rules in specific files / lines will need to be renamed.

Any input on whether this is worth the effort, or we just keep it as is? Or maybe delay the rename until a breaking change to lab is imminent anyway?

**Comment by devinivy** [comment]
That sounds like a plan to me 👍

**Comment by cjihrig** [comment]
Fixed by https://github.com/hapijs/eslint-plugin-hapi/pull/23
